#ifndef LIBSAUROS_VERSION_
#define LIBSAUROS_VERSION_

#define LIBSAUROS_MAJOR_VERSION (0)
#define LIBSAUROS_MINOR_VERSION (1)
#define LIBSAUROS_PATCH_VERSION (0)
#define LIBSAUROS_VERSION "0.1.0"

#endif  // LIBSAUROS_VERSION_
